dist: trusty
language: python
python:
  - "3.6"
addons:
  postgresql: "9.6"
  apt:
    packages:
      - python3-pip
services:
  - postgresql
cache:
  directories:
    - node_modules
branches:
  only:
  - master
  - /^[0-9]+\.[0-9]+$/
  - code-coverage
notifications:
  slack:
    secure: DzxZ8DNGFANLnls0j0/hiKjwg6aO/gI3UO8SiRKjqCO/x27uvBCJiDkTqCx834XVzuDBp6LIdHbyUuwRFyaVHyFYTbA0pqE4fe4/DxkK5DuRDj89cw8JgoK7/g9m/J9Y6GvwaOaE4SW0tnHeTwNDVCt7/w8rn1kxDo/tWtS+3cg=
before_install:
  - nvm install 7.4
  - nvm use 7.4
script:
  # Check versions
  - python3 --version
  - node --version
  - npm --version
  - npm install

  # Install python packages
  - pip3 install numpy scipy matplotlib pandas sympy lxml chevron flake8 flake8-quotes

  # Run JS tests
  - npm test

  # Run JS linter
  - npm run lint-js -s

  # Run Python linter
  - npm run lint-python -s

after_success:
  cat ./coverage/lcov.info | coveralls
