sudo: required
services:
  - docker
language: node_js
node_js:
  - "node"
branches:
  only:
  - master
  - /^[0-9]+\.[0-9]+$/
  - code-coverage
notifications:
  slack:
    secure: DzxZ8DNGFANLnls0j0/hiKjwg6aO/gI3UO8SiRKjqCO/x27uvBCJiDkTqCx834XVzuDBp6LIdHbyUuwRFyaVHyFYTbA0pqE4fe4/DxkK5DuRDj89cw8JgoK7/g9m/J9Y6GvwaOaE4SW0tnHeTwNDVCt7/w8rn1kxDo/tWtS+3cg=
before_install:
  - docker build -t pltest .
install:
  - npm i coveralls -g
script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then sh ./tools/verify-changelog.sh; fi'
  - docker run -it --name=npm_test_container pltest /PrairieLearn/docker/npm_test.sh
  - docker cp npm_test_container:/PrairieLearn/coverage .
  - docker run -it pltest /PrairieLearn/docker/lint_js.sh
  - docker run -it pltest /PrairieLearn/docker/lint_python.sh
after_success:
  - cat ./coverage/lcov.info | coveralls --verbose
