sudo: required
services:
  - docker
branches:
  only:
  - master
  - /^[0-9]+\.[0-9]+$/
  - code-coverage
notifications:
  slack:
    secure: DzxZ8DNGFANLnls0j0/hiKjwg6aO/gI3UO8SiRKjqCO/x27uvBCJiDkTqCx834XVzuDBp6LIdHbyUuwRFyaVHyFYTbA0pqE4fe4/DxkK5DuRDj89cw8JgoK7/g9m/J9Y6GvwaOaE4SW0tnHeTwNDVCt7/w8rn1kxDo/tWtS+3cg=
before_install:
  - docker build -t pltest .
script:
  - docker run -it -e COVERALLS_SERVICE_NAME=${COVERALLS_SERVICE_NAME} -e COVERALLS_REPO_TOKEN=${COVERALLS_REPO_TOKEN} -e COVERALLS_SERVICE_JOB_ID=${COVERALLS_SERVICE_JOB_ID} -e COVERALLS_RUN_AT=${COVERALLS_RUN_AT} pltest /PrairieLearn/docker/npm_test_with_coveralls.sh
  - docker run -it pltest /PrairieLearn/docker/lint_js.sh
  - docker run -it pltest /PrairieLearn/docker/lint_python.sh
