site_name: PrairieLearn
site_url: https://github.com/PrairieLearn/PrairieLearn
repo_url: https://github.com/PrairieLearn/PrairieLearn
theme: readthedocs
docs_dir: doc

pages:
- Main: 'index.md'
- Getting Started: 'running.md'
- User Guide:
  - 'Running PrairieLearn with Docker': 'running-docker.md'
  - 'Running PrairieLearn with Docker Compose': 'running-docker-compose.md'
  - 'Syncing course content': 'sync.md'
  - 'Course configuration': 'course.md'
  - 'Course instance configuration': 'courseInstance.md'
  - 'Assessment configuration': 'assessment.md'
  - 'Question configuration': 'question.md'
  - 'HTML element list': 'elements.md'
  - 'Access control': 'accessControl.md'
  - 'clientFiles and serverFiles': 'clientServerFiles.md'
  - 'UUIDs in JSON files': 'uuid.md'
  - 'Regrading assessments': 'regrading.md'
  - 'PrairieDraw graphics': 'PrairieDraw.md'
  - 'Externally graded questions': 'externalGrading.md'
  - 'What to tell students': 'whatToTellStudents.md'
  - 'How to use PL to learn student names': 'howToLearnNames.md'
  - 'FAQ': 'faq.md'
- Developer Guide:
  - 'Developer guide': 'dev-guide.md'
  - 'Running with local source': 'running-local.md'
  - 'Running natively': 'running-native.md'
  - 'Question element writing': 'devElements.md'
  - 'Docker packaging': 'docker.md'
  - 'Contributing to PL development': 'contributing.md'
  - 'Old v1/v2 question format': 'oldQuestion.md'
